### ISSUE TITLE
How to define variable length fields

### ISSUE THREAD

**Issue by karlmuscat** [jpos/jPOS#233]
Is there a way how to define an `IsoFieldPackager` that contains a variable length `IsoField`? Specifically, I am trying to parse DE35. According to the specs, the first and last fields (Fields 1 and 5, `PAN` and `Discretionary Data`) have variable lengths between 15-19 and 1-10. The current configuration I have is the following:

```
<isofieldpackager id="35"
                      name="TRACK 2 DATA"
                      length="37"
                      class="org.jpos.iso.IFE_LLNUM"
                      emitBitmap="false"
                      pad="true"
                      packager="org.jpos.iso.packager.GenericSubFieldPackager">
        <isofield id="1" length="19" name="PAN" class="org.jpos.iso.IF_CHAR"/>
        <isofield id="2" length="1" name="Separator" class="org.jpos.iso.IF_CHAR"/>
        <isofield id="3" length="4" name="Expiration Data" class="org.jpos.iso.IF_CHAR"/>
        <isofield id="4" length="3" name="Extended Service Code" class="org.jpos.iso.IF_CHAR"/>
        <isofield id="5" length="10" name="Discretionary Data" class="org.jpos.iso.IF_CHAR"/>
    </isofieldpackager>
```

Parsing fails (or corrupts) if the value of either field 1 or field 5 is smaller than 19 or 10 respectively, as jPOS expects the field to be exactly 19 or 10 characters in length. How can I fix this configuration to handle variable lengths?

Thank you

**Comment by alcarraz** [comment]
Hi @karlmuscat thank you for using jpos, this is not an issue but a question, you have the options in the [jpos resources page](http://www.jpos.org/resources), specifically:
jpos users mailing list: http://groups-beta.google.com/group/jpos-users
[jpos slack](http://jpos.slack.com/) #support channel: [request an invite](http://www.jpos.org/main/contact?p=slack-invite)

Please post your question there, I believe mailing list is better since it's searchable and more persistent in case someone else has a similar question in the future. But wouldn't hurt to be in the slack channel to learn from other users questions
