### ISSUE TITLE
jdom2 vulnerability

### ISSUE THREAD

**Issue by rkopka** [jpos/jPOS#436]
Jpos uses jdom2 library in the newest version that has vulnerability
https://nvd.nist.gov/vuln/detail/CVE-2021-33813

**Comment by ar** [comment]
We are aware of this vulnerability for a long time and patched it for the only external vector that could affect the system (see 6d2a7b10). We are also actively monitoring JDOM [Issue 189](https://github.com/hunterhacker/jdom/issues/189) where it has been patched against `master`. We are waiting for the imminent release of the new JDOM version in order to upgrade it in jPOS.

If that doesn't happen soon, we may temporarily host the patched version in our maven repo, until it gets released.

**Comment by ar** [comment]
Fixed in https://github.com/jpos/jPOS/commit/78c4fd6cb29140bd197d0c02db797b948e23485a
